export const conf = {
  defaults: {
    syncDok: true,
    syncTco: false,
    syncAuto: false,
  },
  dokBaseUrl: 'https://decksofkeyforge.com',
  dokPageSize: 1000,
  iconRotations: [
    '../icons/amasser-128-0.png',
    '../icons/amasser-128-30.png',
    '../icons/amasser-128-60.png',
    '../icons/amasser-128-90.png',
    '../icons/amasser-128-120.png',
    '../icons/amasser-128-150.png',
    '../icons/amasser-128-180.png',
    '../icons/amasser-128-210.png',
    '../icons/amasser-128-240.png',
    '../icons/amasser-128-270.png',
    '../icons/amasser-128-300.png',
    '../icons/amasser-128-330.png',
  ],
  mvBaseUrl: 'https://www.keyforgegame.com',
  mvPageSize: 25,
  quotes: [
    '“Always clear your search history.” -Dr. Escotera',
    "“As far as oblivions go, it's in my bottom three.” -Dr. Escotera",
    '“Do you want imps? This is how you get imps.”',
    '“Enjoy your survival bonus of an extra quarter portion.”',
    '“History repeats itself.” -Human Proverb',
    '“I told you to stay off the furniture!”',
    "“I've explored thousands of possible futures. Somehow they all end up here.” -Qincan, Alliance outcast",
    "“If you had seen what I have seen, you'd be mad too.” -the Mad Prophet Gizelhart",
    "“Ingram, put that down! We're surrounded!” -Lieutenant Khrkhar",
    '“Was that you, or the cave?” -Captain Val Jericho',
    '“We can learn so much from our animal friends.”',
    "“You! Æmber lover. You're next.”",
    'Abolish ICE, defund police',
    'Abortion access is a community responsibility',
    'ACAB',
    'Black lives matter',
    'Chinga la migra',
    'Free Palestine',
    'Trans rights are human rights',
  ],
  staleSyncMs: 5 * 1000,
  syncAgainMs: 10 * 1000,
  syncMessages: [
    'Syncing... ',
    'yncing... S',
    'ncing... Sy',
    'cing... Syn',
    'ing... Sync',
    'ng... Synci',
    'g... Syncin',
    '... Syncing',
    '.. Syncing.',
    '. Syncing..',
  ],
  rotateAgainMs: 500,
  timeoutMs: 1000,
  tcoBaseUrl: 'https://thecrucible.online',
  tcoThrottleMs: 10 * 1000,
}
