export const quotes: string[] = [
  '“Always clear your search history.” -Dr. Escotera',
  "“As far as oblivions go, it's in my bottom three.” -Dr. Escotera",
  '“Do you want imps? This is how you get imps.”',
  '“Enjoy your survival bonus of an extra quarter portion.”',
  '“History repeats itself.” -Human Proverb',
  '“I told you to stay off the furniture!”',
  "“I've explored thousands of possible futures. Somehow they all end up here.” -Qincan, Alliance outcast",
  "“If you had seen what I have seen, you'd be mad too.” -the Mad Prophet Gizelhart",
  "“Ingram, put that down! We're surrounded!” -Lieutenant Khrkhar",
  '“Was that you, or the cave?” -Captain Val Jericho',
  '“We can learn so much from our animal friends.”',
  "“You! Æmber lover. You're next.”",
  'Abolish ICE, defund police',
  'Abortion access is a community responsibility',
  'ACAB',
  'Black lives matter',
  'Chinga la migra',
  'Hot rat summer',
  'Trans rights are human rights',
]
